global:
  imageRegistry: ghcr.io

image:
  repository: ialacol/text-inference-batcher-nodejs
  tag: latest

ports:
  - name: http
    containerPort: 8000
    protocol: TCP

envVars:
- name: UPSTREAMS
  value: "http://test:8000"
- name: MAX_CONNECT_PER_UPSTREAM
  value: "1"
- name: TIB_PORT
  value: "8000"
- name: WAIT_FOR
  value: "500"
- name: DEBUG
  value: "false"
- name: TIMEOUT
  value: "600000"
